Claim block gifting
WiIIiam278/HuskClaims pull request #179
Opened 2024-08-27 19:32 UTC by djoey123

Hi,

I created a command to give other players their claim blocks.
Would love to get some feedback from it.

2024-08-31 15:53 UTC, WiIIiam278 requested changes
Hey! Thanks for the PR. I have one _big_ request for this -- can we put this as a subcommand of the existing `/claimblocks` command? :-)

I'd rather not introduce another separate command for this function. I'll re-review again when you've made that refactor.

2024-08-31 16:09 UTC, djoey123 commented
Sure will do :)

2024-09-01 07:36 UTC, djoey123 commented
Moved to existing command :) also changed to permission check like the original claimblocks command.

2024-09-01 09:14 UTC, WiIIiam278 requested changes
Great work! Just a few style nitpicks

2024-09-01 09:14 UTC, WiIIiam278 commented on common/src/main/java/net/william278/huskclaims/command/ClaimBlocksCommand.java
> +        final OnlineUser gifted_player = plugin.getOnlineUsers().stream().filter(online_player -> online_player.getUuid().equals(user.getUuid())).findFirst().orElse(null);
giftedPlayer in camelCase instead of snake case

2024-09-01 09:14 UTC, WiIIiam278 commented on common/src/main/java/net/william278/huskclaims/command/ClaimBlocksCommand.java
> +                (blocks) -> Math.max(0,blocks - changeBy),
Space after a comma in Math.max

2024-09-01 09:14 UTC, WiIIiam278 commented on common/src/main/java/net/william278/huskclaims/command/ClaimBlocksCommand.java
> +        OnlineUser onlineExecuter = (OnlineUser) executor;
We should do an instanceof check here and send an error_in_game_only message if the executor is not an OnlineUser.

```java
    if (!(executor instanceof OnlineUser online)) {
        // send locale error
        return;
    }
```

2024-09-01 09:25 UTC, djoey123 commented
Thanks for the feedback :) fixed it 👍

2024-09-01 09:25 UTC, WiIIiam278 approved these changes

2024-09-01 09:26 UTC, merged